name: wall
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0  
  flutter_snake_navigationbar: ^0.6.1
  image_picker: ^1.0.8
  firebase_storage: ^11.6.0
  intl: ^0.18.1
  cached_network_image: ^3.3.1
  timeago: ^3.6.1 
  easy_localization: ^3.0.7
  intl_utils: ^2.8.7
  adaptive_theme: ^3.6.0
  provider: ^6.1.2
  audioplayers: ^5.2.1
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

  assets:
    - assets/translations/
    - assets/images/
    - assets/sounds/
